### PR TITLE
Fix engrish

### PR DESCRIPTION
**Pull request by Crazily**
Fix typos / engrish / random capitalization

### CODE REVIEW

**Comment by tutoraddicts** [comment]
Some those line you change should not be changed example Backtrack ::

**Comment by tutoraddicts** [comment]
Why do you remove, this?

**Comment by tutoraddicts** [comment]
Backtrack is now synced with Ragebot, but this feature is not fully tested so it can cause a crash. Do not change this line

**Comment by dweee** [comment]
Again refusing improvements to the usability of your training software, I expect nothing less from someone who thinks its better to introduce a new menu instead of doing functional updates 🤔

**Comment by dweee** [comment]
Also accept my discord request, I have something to show you. I don't care if I don't get unbanned from your discord server, it's important though.

**Pull request closed without merging**
